audio:
  channels: 1
  chunk_size: 1024
  device_index: null  # Set via configure.py
  sample_rate: 16000
hotkeys:
  cancel_keys: ctrl+shift+c
  record_key: ctrl_r
recording:
  max_duration: 30
system:
  debug_mode: false
  log_level: INFO
text:
  auto_capitalize: true
  auto_punctuate: true
  remove_filler_words: false
whisper:
  device: auto
  language: en
  model_size: large-v3
